Implementation;Compile;RootName:geiger_integration
Implementation;Compile||(null)||Please refer to the log file for details about 6 Warning(s) , 2 Info(s)||geiger_integration_compile_log.rpt;liberoaction://open_report/file/geiger_integration_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:geiger_integration
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||geiger_integration_placeroute_log.rpt;liberoaction://open_report/file/geiger_integration_placeroute_log.rpt||(null);(null)
Implementation;Generate Bitstream;RootName:geiger_integration
Implementation;Generate Bitstream||(null)||Please refer to the log file for details about 1 Info(s)||geiger_integration_prgdata_log.rpt;liberoaction://open_report/file/geiger_integration_prgdata_log.rpt||(null);(null)
HelpInfo,C:\Microsemi\Libero_v11.6\Synopsys\fpga_J-2015.03M-3\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_v11.6\Synopsys\fpga_J-2015.03M-3\bin\mbin\assistant
Implementation;Synthesis;RootName:transceiver_integration
Implementation;Synthesis|| CS153 ||@E:Can't mix blocking and non-blocking assignments to a variable||transceiver_integration.srr(59);liberoaction://cross_probe/hdl/file/'C:\Users\Scott\Documents\Docs\School\Senior\Projects\Libero\Ball_Avionics\synthesis\transceiver_integration.srr'/linenumber/59||spi_mode_config.v(168);liberoaction://cross_probe/hdl/file/'C:\Users\Scott\Documents\Docs\School\Senior\Projects\Libero\Ball_Avionics\hdl\spi_mode_config.v'/linenumber/168
Implementation;Synthesis||(null)||Please refer to the log file for details about 1 Error(s)||transceiver_integration.srr;liberoaction://open_report/file/transceiver_integration.srr||(null);(null)
